#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#Create PVC and store all workload, config in one place

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-driver-config
  labels:
    app: {{ .Release.Name }}
    role: driver
data:
  kafka-exactly-once.yaml: |
    name: Kafka-exactly-once
    driverClass: io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkDriver

    # Kafka client-specific configuration
    replicationFactor: '4'

    topicConfig: |
      min.insync.replicas=2

    commonConfig: |
      bootstrap.servers=Broker1:9092

    producerConfig: |
      enable.idempotence=true
      max.in.flight.requests.per.connection=1
      retries=2147483647
      acks=all
      linger.ms=1
      batch.size=1048576

    consumerConfig: |
      auto.offset.reset=earliest
      enable.auto.commit=false
      max.partition.fetch.bytes=10485760

  max-rate-100-topics-3-partition-64kb.yaml: |
    name: max-rate-100-topics-3-partition-64kb

    topics: 100
    partitionsPerTopic: 3
    messageSize: 65536
    #payloadFile: "payload/payload-1Kb.data"
    useRandomizedPayloads: true
    randomBytesRatio: 0.5
    randomizedPayloadPoolSize: 100

    subscriptionsPerTopic: 1
    consumerPerSubscription: 1
    producersPerTopic: 1

    # Discover max-sustainable rate
    producerRate: 10000000

    consumerBacklogSizeGB: 0
    testDurationMinutes: 30
---

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-driver
  labels:
    app: {{ .Release.Name }}
    role: driver
spec:
#  securityContext:
#    runAsUser: 1000840000
  volumes:
    - configMap:
        name: {{ .Release.Name }}-driver-config
      name: driver-yaml
      items:
        - key: kafka-exactly-once.yaml
          path: {{ .Values.driver}}
    - configMap:
        name: {{ .Release.Name }}-driver-config
      name: workload-yaml
      items:
        - key: max-rate-100-topics-3-partition-64kb.yaml
          path:  {{ .Values.workload}}     
    - name: kafka-workbench-data
      persistentVolumeClaim:
        claimName: digital-experience-kafka-workbench-data
  containers:
    - name: {{ .Release.Name }}-driver
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      image: {{ .Values.image }}
      serviceAccount: digital-experience-sa
      volumeMounts:
        - name: driver-yaml
          mountPath: "/benchmark/{{ .Values.driver}}"
          subPath: {{ .Values.driver}}
          readOnly: true
        - name: workload-yaml
          mountPath: "/benchmark/{{ .Values.workload}}"
          subPath: {{ .Values.workload}}
          readOnly: true          
        - name: kafka-workbench-data
          mountPath: /opt
      resources:
        limits:
          memory: {{ .Values.driverMemoryLimit }}
          cpu: {{ .Values.driverCpuLimit }}
        requests:
          memory: {{ .Values.driverMemoryRequest }}
          cpu: {{ .Values.driverCpuRequest }}
      env:
        - name: NUM_WORKERS
          value: "{{ .Values.numWorkers }}"
        - name: WORKERS
          value: '{{ template "workers" .Values }}'
        - name: HEAP_OPTS
          value: '-Xms1G -Xmx16G'
        - name: JVM_MEM
          value: '-Xms1G -Xmx16G -XX:+UseG1GC'          
      command: ["sh", "-c"]
      args: ["bin/benchmark --drivers {{ .Values.driver }} --workers $WORKERS /benchmark/max-rate-100-topics-3-partition-64kb.yaml --output /opt/workloads_output.json"]
      # args:
      #   - >
      #     echo "bin/benchmark --drivers {{ .Values.driver }} --workers $WORKERS workloads/max-rate-100-topics-1-partition-64kb.yaml" > /opt/example-run.sh &&
      #     tail -f /dev/null

